"""Core processing layer: pure NumPy / OpenCV / SciPy math.

This package is intentionally agnostic of PyQt6 and of every hardware SDK so that
the optical-sectioning mathematics can be unit-tested and reused in isolation.
"""

from .image_processing import (
    process_dsi,
    compute_dsi_images,
    crop_to_roi,
    normalize_to_8bit,
    save_dsi_results,
    save_single_image,
    save_raw_stack_tiff,
    save_volume_tiff,
    save_axial_sectioning_plot,
    save_axial_average_plot,
    save_parameter_log,
    scale_16bit_image,
    autocontrast_8bit,
    downscale_for_display,
    accumulate_event_frame,
    save_event_stream,
    EventCsvWriter,
    filter_crazy_pixels,
    apply_smoothing,
    save_mat_tif,
    raw_stack_plane_path,
    read_multipage_tiff,
    find_complete_planes,
    rebuild_zstack_from_raw,
    event_raw_plane_path,
    find_complete_event_planes,
    evk4_footprint_in_orca,
    map_evk4_window_to_orca,
    register_evk4_to_orca,
    compose_registration_overlay,
    decompose_fov_affine,
)

__all__ = [
    "process_dsi",
    "compute_dsi_images",
    "crop_to_roi",
    "normalize_to_8bit",
    "save_dsi_results",
    "save_single_image",
    "save_raw_stack_tiff",
    "save_volume_tiff",
    "save_axial_sectioning_plot",
    "save_axial_average_plot",
    "save_parameter_log",
    "scale_16bit_image",
    "autocontrast_8bit",
    "downscale_for_display",
    "accumulate_event_frame",
    "save_event_stream",
    "EventCsvWriter",
    "filter_crazy_pixels",
    "apply_smoothing",
    "save_mat_tif",
    "raw_stack_plane_path",
    "read_multipage_tiff",
    "find_complete_planes",
    "rebuild_zstack_from_raw",
    "event_raw_plane_path",
    "find_complete_event_planes",
    "evk4_footprint_in_orca",
    "map_evk4_window_to_orca",
    "register_evk4_to_orca",
    "compose_registration_overlay",
    "decompose_fov_affine",
]
